add docker-compose, celery and redis. test_celery task working. print…
thinknetica-django-lab-05/veselij pull request #62
Opened 2021-11-11 16:17 UTC by veselij

Closes #55

2021-11-15 01:25 UTC, ilyuhi4 commented on onlinestore/main/views.py
> +        test_celery.delay()
в будещем не забудь убрать :)

2021-11-15 01:36 UTC, ilyuhi4 commented on docker/docker-compose.yaml
> +
не должно ли тут быть парочки вольюмов с например настройками redis?

2021-11-15 01:37 UTC, ilyuhi4 requested changes
в такой конфигурации мы будем терять задачи при перезапуске

2021-11-15 09:27 UTC, veselij commented on onlinestore/main/views.py
> +        test_celery.delay()
уже убрал дальше в следующем PR)

2021-11-15 09:50 UTC, veselij commented on docker/docker-compose.yaml
> +
да, я видел их в начале, но подумал зачем захламлять локальный комп. Добавил

2021-11-20 05:50 UTC, ilyuhi4 approved these changes

2021-11-21 13:52 UTC, merged