7 4 sms verification
thinknetica-django-lab-05/veselij pull request #66
Opened 2021-11-14 19:56 UTC by veselij

Closes #58

2021-11-18 08:27 UTC, ilyuhi4 commented on onlinestore/main/views.py
>      template_name_suffix = '_update_form'
тут кончено не очень корректно обзывать тэмплэйт с окончанием таким - вводит в заблуждение

2021-11-18 08:33 UTC, ilyuhi4 commented on onlinestore/templates/main/seller_update_form.html
> +    {{ form2|crispy }}
лучше именование осмысленное делать - оно не отнимает процессорного времени

2021-11-18 08:35 UTC, ilyuhi4 commented on onlinestore/main/views.py
> +        if 'form3' in kwargs.keys():
я поплыл form2??
form3???

2021-11-18 08:42 UTC, ilyuhi4 requested changes
доработать нужно

2021-11-18 09:21 UTC, veselij commented on onlinestore/main/views.py
>      template_name_suffix = '_update_form'
а как лучше назвать?

2021-11-18 09:28 UTC, veselij commented on onlinestore/templates/main/seller_update_form.html
> +    {{ form2|crispy }}
переименовал

2021-11-18 09:30 UTC, veselij commented on onlinestore/main/views.py
> +        if 'form3' in kwargs.keys():
через форму делал доп поле для кода смс и текста статуса смс. переименовал формы, надеюсь понятней станет. но в целом все как то кривенько получилось. может как то по-другому подойти?

2021-11-20 05:52 UTC, ilyuhi4 commented on onlinestore/main/views.py
>      template_name_suffix = '_update_form'
Если ты знаешь какой именно шаблон будет использоваться, то я бы рекомендовал использовать template_name вообще
По поводу нэйминга - ты же не столько форму отображаешь на этом шаблоне, сколько обеспечиваешь работу с данными. Я бы так и назвал сам шаблон seller-update.html

2021-11-20 05:55 UTC, ilyuhi4 commented on onlinestore/main/views.py
> +            context['sms_code_form'] = self.sms_code_form()
я бы лучше сделал валидацию номера - это было бы корректно.
Такую простенькую валидацию можно даже на js замутить без загромождения view

2021-11-20 05:57 UTC, ilyuhi4 approved these changes
Принципиально это работает, но я бы очень рекомендовал тебе доделать штуку с телефоном - достаточно типовая задача.
Чтобы не топтаться на месте, можешь слить ветку и просто сделать новую именно с фичей проверки номера.

2021-11-21 13:54 UTC, merged

2021-11-21 14:58 UTC, ilyuhi4 commented on onlinestore/main/views.py
> +            context['sms_code_form'] = self.sms_code_form()
По валидации - отмена. Всё работает.
Рекомендация - упростить функцию в SellerUpdate: разделить её на части корректные. 
Иначе нарушаем правило: в функции только одно наполнение функционалом